version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "7777:7777"
  db:
    image: mysql:5.7
    ports:
      - "3308:3308"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
