version: '3'
services:
  flask:
    build: ./backend
    container_name: project-Antananarivotest
    links:
      - db
    environment:
      - PYTHONUNBUFFERED=True
    restart: on-failure
    volumes:
      - ./backend:/backend
      - ./migrations:/migrations
    ports:
      - "6666:6666"
    command: python main.py
  db:
    image: mysql:5.7
    ports:
      - "6667:6667"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
