version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "6666:6666"
  db:
    image: mysql:5.7
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
